### ISSUE TITLE
Cannot highlight the searches when comparing Aquitanian vs. Aquitanian or when Square is on the left slot

### ISSUE THREAD

**Issue by martha-thomae** [ECHOES-from-the-Past/mei-analyser#1]
The highlighting of the neumes by contour does not work if the file uploaded to the left is in square notation and the one in the right is Aquitanian. Or when both are in Aquitanian notation. 

----

You can try with these two Aquitanian:
- [05_dicit-dominus_pem84540_aquit_AQUIT](https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/main/MEI_outfiles/05_dicit-dominus_pem84540_aquit_AQUIT.mei)
- [06_dicit-dominus_pem84623_aquit_AQUIT](https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/main/MEI_outfiles/06_dicit-dominus_pem84623_aquit_AQUIT.mei)

They render correctly, but only the Aquitanian on the left gets highlighted:
![Screenshot 2024-01-10 at 4 34 36 PM](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/13948831/490fa7a2-669a-449b-bbd4-d0f6b63ca73d)

----

Or with a square on the left and an Aquitanian on the right:
- [07_dicit-dominus_pem84873_square_SQUARE](https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/main/MEI_outfiles/07_dicit-dominus_pem84873_square_SQUARE.mei)
- [06_dicit-dominus_pem84623_aquit_AQUIT](https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/main/MEI_outfiles/06_dicit-dominus_pem84623_aquit_AQUIT.mei)

They render correctly, but nothing gets highlighted:
![Screenshot 2024-01-10 at 4 33 50 PM](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/13948831/295d76e4-581c-4459-8c5b-05a96d9dfb79)

**Comment by notkaramel** [comment]
I fixed this in [commit 28ab3c4](https://github.com/ECHOES-from-the-Past/mei-analyser/commit/28ab3c4661c658ee7e04fe708c967d4ae4f9be75) by adding a detection function in `src/utils.js` called `get_annotation_type(MEI_content)`. Essentially, it gets the `@staffDef` from the chant and check its `lines` attribute. If there are more than 1 line, it's Square annotation, otherwise, it's Aquitanian.

```js
// [...]
const staffDef = htmldoc.querySelector('staffDef');
const lines = staffDef.attributes.getNamedItem('lines').nodeValue;
if (lines > 1) {
  return "square";
}
else {
  return "aquitanian";
}
```
