### ISSUE TITLE
Detection of Chant Mode in Square Notation

### ISSUE THREAD

**Issue by martha-thomae** [ECHOES-from-the-Past/mei-analyser#10]
# Description
Teaching the machine how to identify the mode of chants written in square notation

# Modes (Square notation)
> Referencing the ECHOES - Project Report 2023
## 1st mode
- The last note is D
- The pitch range is D-D
- The most repeated pitch should be A

## 2nd mode
- The last note is D
- The pitch range is A-A
- The most repeated pitch should be F

## 3rd mode
- The last note is E
- The pitch range is E-E
- The most repeated pitch should be C (or, occasionally, B)

## 4th mode
- The last note is E
- The pitch range is B-B
- The most repeated pitch should be A

## 5th mode:
- The last note is F
- The pitch range is F-F
- The most repeated pitch should be C

## 6th mode:
- The last note is F
- The pitch range is C-C
- The most repeated pitch should be A

## 7th mode:
- The last note is G
- The pitch range is G-G
- The most repeated pitch should be D

## 8th mode:
- The last note is G
- The pitch range is D-D
- The most repeated pitch should be C

**Comment by notkaramel** [comment]
@elsinhadl @martha-thomae Can you help me clarify what does "pitch range" mean? For example, does "pitch range is D-D" means that all notes are from "D2 to D3", or "D3 to D4"?

**Comment by elsinhadl** [comment]
Hi Antoine,
it means that melodies in that specific mode *normally* run within an
octave (D-D, for example) but the exact octave is not specified. It must be
said, however, that a melody could go higher or lower the octave range, but
this is quite rare.
I hope this helps! Please let me know if you have any further questions.
All the best,
Elsa



*________________________________________________________*

PI of *Echoes from the Past: Unveiling a Lost Soundscape with Digital
Analysis
<https://sites.google.com/fcsh.unl.pt/elsadeluca/echoes-research-project> *
(2022.01957.PTDC)

Recent publication: *The Materiality of Sound in ChantManuscripts in the
West
<https://www.brepols.net/products/IS-9782503606149-1?fbclid=IwAR2gxS-ucQAfNZEgO9rjGSbBUcpXbSKBkictNRCHw5uqWjfIDCw0oyhYpso>*,
Brepols 2023


CESEM - Centre for the Study of the Sociology and Aesthetics of Music
IN2PAST – Associate Laboratory for Research and Innovation in Heritage,
Arts, Sustainability and Territory
School of Social Sciences and Humanities
NOVA University of Lisbon

https://sites.google.com/fcsh.unl.pt/elsadeluca/ |
*https://cesem.fcsh.unl.pt/en/pessoa/elsa-de-luca-2/
<https://cesem.fcsh.unl.pt/en/pessoa/elsa-de-luca-2/> *



Antoine Phan ***@***.***> escreveu (domingo, 10/03/2024 à(s)
01:09):

**Comment by notkaramel** [comment]
@elsinhadl Thank you Elsa, it really helps!

I've already made the machine able to detect the last note and the most frequent pitch. For the pitch range, would it make sense to you when:
- The melodies run within an octave, the machine would say "the chant is **100%** in mode `x`"
- The melodies has a few notes outside of the octave, the machine would say "the chant is **90%** in mode `y`"

If not, how would you prefer it to detect?

**Comment by elsinhadl** [comment]
Hello Antoine,
Yes, it makes totally sense!
Thank you,
Elsa

**Comment by notkaramel** [comment]
@elsinhadl Hi Elsa,

So, I have a list of chants in Square notation that the machine is able to detect their mode. Can you help me verify their accuracy? Thank you!

| MEI file | Mode detected | PEM Database URL |
| -------- | ------------- | ---------------- |
| 010_C10_ecce-virgo_pem84882_square_SQUARE.mei | 1 (99%) | https://pemdatabase.eu/image/84882 |
| 014_C14_factus-est-repente_pem84881_square_SQUARE.mei | 7 (100%) | https://pemdatabase.eu/image/84881 |
| 018_C18_justorum-animae_pem85059_square_SQUARE.mei | 4 (40%) | https://pemdatabase.eu/image/85059 |
| 023_C23_martinus-abrahe_pem85056_square_SQUARE.mei | 7 (100%) | https://pemdatabase.eu/image/85056 |
| 030_C30_pater-si-non_pem84872_square_SQUARE.mei | 8 (100%) | https://pemdatabase.eu/image/84872 |
| 045_M02_nemo-te_pem71059_square_SQUARE.mei | 3 (100%) | https://pemdatabase.eu/image/71059 |
| 054_M11_tunc-invocabis_pem71032_square_SQUARE.mei | 8 (94%) |  https://pemdatabase.eu/image/71032 |
| 078_F12_in-sanctitate-serviamus_pem71010_square_SQUARE.mei | 7 (100%) | https://pemdatabase.eu/image/71010 |
| 084_F18_laudate-nomen_pem71010_square_SQUARE.mei | 1 (100%) | https://pemdatabase.eu/image/71010 |

**Comment by notkaramel** [comment]
@martha-thomae is it normal that lots of chants have the same link to the PEM Database? (This is currently on http://server.notkaramel.me/mei-analyser/)

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/0dd72199-462e-44e0-9451-3c490832af4f)

**Comment by martha-thomae** [comment]
What does the percentage mean?

**Comment by notkaramel** [comment]
> @notkaramel, could you explain what the percentage means? Thank you!

@martha-thomae yes! It's calculated by the number of notes/pitches that are in the octave range for the mode divided by the total amount of notes. Currently, the mode is detected by the last note and the most repeated note. The percentage is for the pitch range.

For example, chant 010 "Ecce Virgo" has the **last note D** and **most repeated pitches are A**, so it's very likely to be **mode 1**. Now for the pitch range condition "D-D", the machine will count how many notes are in that one octave range. Between D2 and D3 of *Ecce Virgo*, there are 67 notes. Divide that to 68 of total amount of notes, we get **98.53%**.

**Comment by elsinhadl** [comment]
Hi Antoine,
The detected modes are ALL correct!
Thank you

**Comment by elsinhadl** [comment]
Hi Antoine,
all the pieces in square notation should have a mode. Could you please investigate why the vast majority of modes is missing?Thanks

**Comment by martha-thomae** [comment]
Examples: 
- Chant 02 is in Mode 4
- Chant 04 is in Mode 6
- Chant 11 is in Mode 2

**Comment by notkaramel** [comment]
@elsinhadl Hi Elsa,

Yes, I will investigate the issue and update you on it!

**Comment by notkaramel** [comment]
@martha-thomae I looked (briefly) into the detection and it's giving me the following results:
- Chant 02 has last note E (mode 4) but most repeated note is G (should be A to be mode 4).
- Chant 04 has last note F (mode 6) but most repeated note is F (should be E to be mode 6).
- Chant 11 has last note F (mode 2) but most repeated note is G (should be F to be mode 2).

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/6a45248d-b69e-4201-a99e-75efdb84cfe6)

**Comment by martha-thomae** [comment]
@notkaramel, the examples come from Elsa; I added them during our meeting. Could you maybe check which note is the second most repeated? Or, even better, allow for the console logs to see all the pitches from `c` to `b` and see how many times they appear on a chant? That might help in debugging this. Thank you!!!

**Comment by martha-thomae** [comment]
There is an error in the `mostRepeatedPitch` variable of the following two if statements:

- https://github.com/ECHOES-from-the-Past/mei-analyser/blob/a2152506e4d2706ddb9847d2c00d6fcf1a26792d/src/utility/components.js#L393-L394

  It should be `mostRepeatedPitch === 'c'`.

- https://github.com/ECHOES-from-the-Past/mei-analyser/blob/a2152506e4d2706ddb9847d2c00d6fcf1a26792d/src/utility/components.js#L396-L397

  It should be `mostRepeatedPitch === 'a'`.

**Comment by martha-thomae** [comment]
> @martha-thomae I looked (briefly) into the detection and it's giving me the following results:
> 
> * Chant 02 has last note E (mode 4) but most repeated note is G (should be A to be mode 4).
> * Chant 04 has last note F (mode 6) but most repeated note is F (should be E to be mode 6).

I think here it is supposed to be A (not E)

> * Chant 11 has last note F (mode 2) but most repeated note is G (should be F to be mode 2).

This seems to be the results for chant 07, could you check it for chant 11?

> 
> ![image](https://private-user-images.githubusercontent.com/24505220/312954607-6a45248d-b69e-4201-a99e-75efdb84cfe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjMxNjIsIm5iZiI6MTcxMDQ2Mjg2MiwicGF0aCI6Ii8yNDUwNTIyMC8zMTI5NTQ2MDctNmE0NTI0OGQtYjY5ZS00MjAxLWE5OWUtNzVlZmRiODRjZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAwMzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZjVkOWYyZjZkNTBmZWQ3M2U0OTM2Mjg1ZTYwODNlODAwZGQxMzhlYzc5M2IwNmMzMjQyNmFkNDI1ZTYxNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TlcX4GwvibO9_5up9h4YpMt0D9J6f0WCz3BUw6Z9GyA)

And, as indicated on another comment, it would be good if we could take a look at the number of times each of the pitches appear in each chant.

**Comment by notkaramel** [comment]
@martha-thomae I added the fix for mode 5 and 6 detection + the log message on commit https://github.com/ECHOES-from-the-Past/mei-analyser/pull/16/commits/1c87d7ddffb1059835cd51acae5c181480d2910a. You can checkout to the branch `square-mode-detection` and view the console log everytime you click the "Refresh Database" button. Here's a screenshot of the log message, including Chant 011

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/2f08345b-cf46-456e-870a-bd5278a288eb)

I can also compile these messages into a table so it's easier for us to analyse.

**Comment by martha-thomae** [comment]
Thank you. I would like to try it. I cannot run the website on my computer on the branch though. I am having the following error when running `npm run dev`:

```
mthomae@rei mei-analyser % npm run dev

> mei-analyser@0.2.2 dev
> vite

/Users/mthomae/Downloads/mei-analyser/node_modules/rollup/dist/native.js:87
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/mthomae/Downloads/mei-analyser/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/Users/mthomae/Downloads/mei-analyser/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/mthomae/Downloads/mei-analyser/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at requireWithFriendlyError (/Users/mthomae/Downloads/mei-analyser/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/Users/mthomae/Downloads/mei-analyser/node_modules/rollup/dist/native.js:96:76)
      at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
      at Module.load (node:internal/modules/cjs/loader:1207:32)
      at Module._load (node:internal/modules/cjs/loader:1023:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/mthomae/Downloads/mei-analyser/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v21.2.0
mthomae@rei mei-analyser %
```

**Comment by notkaramel** [comment]
Ahhh~ @martha-thomae Have you tried removing both **package-lock.json** and **node_modules** directory?
```sh
rm package-lock.json
rm -rf node_modules
```
It seems like a computer architecture problem, I was able to recreate it on my ARM computer too. Will note that to update package-lock.json

**Comment by martha-thomae** [comment]
It worked, thank you!

**Comment by martha-thomae** [comment]
I cannot see anything in the console when selecting any of the pieces though (or when reloading the page).

**Comment by notkaramel** [comment]
Do you have "Verbose" log level enabled? It's on the top of the console on Chrome. I used `console.debug()` to log the information.
![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/c0534fb6-356d-4665-a63e-43a2ea04ca04)

**Comment by martha-thomae** [comment]
Sorry, I didn't click on "refresh database" (I was just refreshing the page...)
Yes, I have verbose, and I see everything now. Thank you!!!

**Comment by martha-thomae** [comment]
I just found a typo (an extra space in a string) that is messing up with detecting mode 2:
https://github.com/ECHOES-from-the-Past/mei-analyser/blob/1c87d7ddffb1059835cd51acae5c181480d2910a/src/utility/components.js#L386


The last note has an extra space after the `d`. Will continue checking the code. Thank you for the console logs, they are helping a lot!

**Comment by martha-thomae** [comment]
Fixed :) 
Will continue checking.

**Comment by martha-thomae** [comment]
After checking the implementation, these are the final results. @elsinhadl could we revise these together? There are still chants for which the algorithm isn't detecting a mode.

[MEI Analyser - Mode - Square Notation.pdf](https://github.com/ECHOES-from-the-Past/mei-analyser/files/14638260/MEI.Analyser.-.Mode.-.Square.Notation.pdf)

We can check the finalis and repercussio for all square notation chants in this other document:

[Square Notation - Mode.docx](https://github.com/ECHOES-from-the-Past/mei-analyser/files/14638297/Square.Notation.-.Mode.docx)

**Comment by elsinhadl** [comment]
Can we do this during our next meeting, or you prefer I check all the chants prior to our meeting so that we can discuss any anomalies?

**Comment by martha-thomae** [comment]
@elsinhadl, yes, please. Let's do this during our meeting.

**Comment by martha-thomae** [comment]
New instructions to be able to provide a mode with an associated probability by taking into consideration: 
1. finalis
2. repercussio
3. ambitus (or range)
Each of these three features will contribute to the percentage of certainty of the predicted mode. The finalis gives us two possible modes, providing us with two possible repercussio notes and two possible ranges (as indicated in the following table). We will evaluate these two features, repercussio and range, independently from one another (see steps 2 and 3, respectively) and combine the results at the end (step 4). 

As you will see, the way to evaluate the repercussio will change a bit from what we have done so far (i.e., we won't assume that it is always the most repeated note on a piece). And we will always evaluate the range too, regardless of which note is the most repeated on a piece, since we will treat these two features (range and repercussio) as independent from one another.

The process will be the following:

1. Check the finalis and, based on it, determine the two possible modes:

    | Finalis | Authentic mode | Plagal mode |
    | ------ | ---------------- | ------------ |
    | D   | **1st mode** with ambitus D-D (almost all notes are above the D finalis) and repercussio A  | **2nd mode** with ambitus A-A (notes lie above and below the finalis) and repercussio F |
    | E    | **3rd mode** with ambitus E-E (almost all notes are above the E finalis)  and repercussio C or B  | **4th mode** with ambitus B-B  (notes lie above and below the finalis) and repercussio A |
    | F    | **5th mode** with ambitus F-F (almost all notes are above the F finalis)  and repercussio C | **6th mode** with ambitus C-C  (notes lie above and below the finalis) and repercussio A |
    | G   | **7th mode** with ambitus G-G (almost all notes are above the G finalis)  and repercussio D  | **8th mode** with ambitus D-D  (notes lie above and below the finalis) and repercussio C |

    This provides a `34%` probability of the mode being correct.

2. The other 33% comes from the repercussio. 
  After Step 1, we have two possible modes (the authentic and plagal modes based on the finalis). Therefore, we have two (in one occasion three) possible repercussio notes. We evaluate the following scenarios for the two expected repercussio notes:
    1. If one of the two expected repercussio notes is the most repeated note: `33%`
    2. If one of the two expected repercussio notes is the second most repeated note after the finalis: `25%`
    3. If one of the two expected repercussio notes is the second most repeated note after a note other than the finalis: `17%`
    4. If one of the two expected repercussio notes is the third most repeated note: `12%`
    5. If one of the two expected repercussio notes is the fourth most repeated note: `6%`

    And we store the predicted mode based on this (_mode_from_repercussio_).

3. Finally, we consider the range or ambitus:
  Like the repercussio, here we have two expectations for the range (based on the authentic and plagal modes figured out in Step 1). Therefore, we will:
    1. Calculate the percentage of notes in each range 
      (@elsinhadl should we do this for just the two ranges suggested by the finalis, or for all the ranges? Otherwise, the final part of step 4 doesn't make sense)
    2. Favor the mode with the highest percentage (_mode_from_ambitus_)

4. Final step, where we combine the information about the previous two features, repercussio and ambitus, to determine which mode we choose (authentic or plagal):
    - If the range matches the mode suggested by the repercussio, we add `33%` to our percentage of certainty and provide the result of the mode
    - If the range does not match the mode suggested by the repercussio (so one indicates the authentic mode and the other the plagal mode, or vice-versa), we add `17%` to our percentage of certainty and provide both the authentic and plagal modes as results
    - If the range is any other mode, we add `0%` to the percentage of certainty

Could you implement this so that we can evaluate it next time with Elsa?
If you have any questions, please forward them to Elsa for this coming week :)

@elsinhadl, please let us know here if there is any error in this text, I think it summarizes what we discussed today :)
Maybe in the last case (where the range is any other mode), we should not provide any mode at all?

**Comment by elsinhadl** [comment]
Hello,
some remarks:
- after step 1 and the two modes (authentic and plagal) are selected, the 34% score is earned.
- step 3.I: D-D is the range of modes 1th Authentic and 8th plagal. I am afraid that this overlap may complicate the results. Therefore, I think it is OK if we calculate the percentage of notes in the range just for the two modes suggested by the finalis.

**Comment by notkaramel** [comment]
@elsinhadl @martha-thomae
Hi Elsa and Martha,

I've updated the app to detect the mode, following (1) detect the finalis, (2) analyse repercussio, and (3) analyse ambitus. I have not made it such that it can display multiple modes as you mentioned above.

It's now live on https://echoes-from-the-past.github.io/mei-analyser/, you can test it out by first **click** on `Refresh Database` to update the list of chants, **select `Square`** for notation type on the search panel, **click `Search`**, and select a chant of interest by **clicking on its `File Name`** on the last column. 

Please let me know how it goes, what should I change/improve, as well as any potential bugs you might encountered.

**Comment by martha-thomae** [comment]
Perfect, thank you @notkaramel! I will be checking this :)

**Comment by martha-thomae** [comment]
For Chant 011:
> Mode Description: Finalis pitch is 'd'. Plagal repercussio detected, the most repeated note is f (18 times). Ambitus suggests authentic mode '1' with 90.41% of notes in range. Mode detected from ambitus ('1') is different from mode detected from finalis and repercussio ('2').

But the ambitus seem to be the plagal one ('2'), because the range goes from C3-A3, which fits better in the A2-A3 range of the plagal mode ('2') than the D2-D3 range of the authentic mode ('1'). Could you check if there is an error in the percentage calculated for both authentic and plagal ambitus here? Thank you!

**Comment by martha-thomae** [comment]
For Chant 26:
> Mode Description: Finalis pitch is 'f'. Ambitus suggests plagal mode '6' with 100% of notes in range. Mode detected from ambitus ('6') is different from mode detected from finalis and repercussio ('undetected').

However, the conclusion from the "repercussio" is wrong. It shouldn't be "undetected." The repercussions falls into the IV category:
> If one of the two expected repercussio notes is the third most repeated note: 12%

Could you add this condition (and number V) to the code?
> iv. If one of the two expected repercussio notes is the third most repeated note: 12%
> v. If one of the two expected repercussio notes is the fourth most repeated note: 6%

**Comment by martha-thomae** [comment]
Same issue with Chant 035, where the repercussio resulted on an "undetected" mode. However, in this case, the repercussions falls into case ii:
> If one of the two expected repercussio notes is the second most repeated note after the finalis: 25%
The pitch frequency for the notes is the following: `{"c":8, “d":5, “f":24, “g":14, “a":14, “b":5}`. So `A` is repeated 14 times (same as `G`), which is the second highest number after `F` (the finalis).

The analyzer currently shows this:
> Mode Description: Finalis pitch is 'f'. Ambitus suggests plagal mode '6' with 100% of notes in range. **Mode detected from ambitus ('6') is different from mode detected from finalis and repercussio ('undetected').**

**Comment by martha-thomae** [comment]
I have revised the square notation mode detection until Chant 035 right now. After you look into the comments above and fix these, I can will continue looking into the full list. Thank you, @notkaramel!

Maybe start with the repercussio-related comments.
https://github.com/ECHOES-from-the-Past/mei-analyser/issues/10#issuecomment-2039616294 first to handle conditions IV and V independently of whether the most repeated note is the finals or not, then https://github.com/ECHOES-from-the-Past/mei-analyser/issues/10#issuecomment-2039640717 to solve the issue when two notes have the same frequency, and then move into the ambitus issue of https://github.com/ECHOES-from-the-Past/mei-analyser/issues/10#issuecomment-2039573132

**Comment by notkaramel** [comment]
Thank you @martha-thomae, that was a lot of helpful feedbacks! I will update when there's a new fix

**Comment by martha-thomae** [comment]
### Update on the heuristic process for predicting the mode and providing a percentage of certainty:

The _finalis_ won't contribute at any part of the final percentage, while the _ambitus_ and the _repercussio_ will contribute 50% each to the final percentage as indicated by the heuristic below:

#### Finalis:
The _finalis_ will just allow us to select the two modes (authentic and plagal) whose ambitus and repercussion will be analyzed. It won't provide a percentage by itself.

#### Ambitus:
Calculate the percentage of the notes in the _ambitus_ for both authentic and plagal versions of the mode. Then divide by two.
- **Authentic:** `Percentage in authentic range / 2` (Max. 50%)
- **Plagal:** `Percentage in plagal range / 2` (Max. 50%)

#### Repercussio:
Calculate the percentage for the _repercussio_ by using the same heuristic as we did before (with the cases _i_ to _v_ that you have implemented, but with different percentages—the **maximum is 50%** rather than 100%)

- **Authentic**
  i. If the expected repercussio note is the most repeated note: 50%
  ii. If the expected repercussio note is the second most repeated note after the finalis:  37.5%
  iii. If the expected repercussio note is the second most repeated note after a note other than the finalis: 25%
  iv. If the expected repercussio note is the third most repeated note:  12.5%
  v. If the expected repercussio note is the fourth most repeated note:  6.25%

- **Plagal**
  i. If the expected repercussio note is the most repeated note: 50%
  ii. If the expected repercussio note is the second most repeated note after the finalis:  37.5%
  iii. If the expected repercussio note is the second most repeated note after a note other than the finalis: 25%
  iv. If the expected repercussio note is the third most repeated note:  12.5%
  v. If the expected repercussio note is the fourth most repeated note:  6.25%

----------------------------------------------------------------------------------------------

The final probability of the authentic and plagal modes is the sum of the probability given by the ambitus and the one given by the repercussio (each of them account for 50%):

* Probability of authentic = auth_ambitus + auth_repercussion (max. 100%)
* Probability of plagal = plag_ambitus + plag_repercussion (max. 100%)


The highest **probability** will be shown with that **mode** in the **table**. While the whole set of four percentages will be shown in the “Mode Description” field of the "Chant Information" panel.
