### ISSUE TITLE
Search for syllables that contains the ornamental shapes

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#13]
# Instructions
- The following instructions are resolved in #11
  - [x] This search should be applicable to the whole corpus (the full database of files).
  - [x] In the future: Maybe we can think of implementing some checkboxes that allow to select the chants on the database to which the user can apply this type of search to. With subtypes for chant modes. There should be an option to select all.
  - [x] Look for all `<nc>` elements with the following children elements:
    - `<quilisma>`
    -  `<liquescent>`
    -  `<oriscus>`
- [x] Retrieve the whole `<syllable>` that is the "grandparent" of that `<nc>`.
- [x] Retrieve the whole word where that syllable is. 

> **@wordpos** *(optional)* Records the position of a syllable within a word. Allowed values are: "i" ((initial) first syllable.), "m" ((medial) neither first nor last syllable.), "s" ((single) single syllable.), "t" ((terminal) last syllable.)

[https://music-encoding.org/guidelines/v5/elements/syl.html#attributes_full_tab](https://music-encoding.org/guidelines/v5/elements/syl.html#attributes_full_tab)

- The list of results should be a list of the retrieved syllables and corresponding word for it, together with a link to the chant containing them: image (and, maybe, file rendition in Verovio).

- _Originally posted by @martha-thomae in https://github.com/ECHOES-from-the-Past/mei-analyser/issues/6#issuecomment-1937842343_

**Comment by martha-thomae** [comment]
Just a short note: 

During today's meeting, Elsa approved the use of the checkboxes for _liquescent_, _quilisma_, and _oriscus_ in the way they are implemented now; this is, where multiple checked boxes imply searching for all these ornamental neumes at the same time (with an "AND" connector). So we are all good at the moment!

**Comment by martha-thomae** [comment]
As indicated in https://github.com/ECHOES-from-the-Past/mei-analyser/issues/22#issuecomment-2036835204, the result should be displayed on an extra column with heading 'Text'. This column should contain the full text of the chant, with the syllables that contain ornamental neumes in a different color.

**Comment by notkaramel** [comment]
Hi @martha-thomae! This issue definitely took me waaay longer than I thought it would.
Here's a current screenshot of the progress on detecting syllables that are related to the ornamental figures. (in order: Chant **005_C05**, **040_C40**, **042_C42**)

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/649af41e-7734-499e-8fc6-3816204ed4d2)

I will try to detect the word to which those syllable words belongs.

**Comment by notkaramel** [comment]
@martha-thomae Here's a screenshot from what I implemented currently, I think it's looking good. The styling are: **liquescent-word**: blue, solid underline; **quilisma-word**: yellow, wavy underline; **oriscus-word**: pink/purple, dashed underline.

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/6c355000-3f2b-431b-b1bd-26d757dea2bb)

---

With that, I noticed another figure that's coded as `<unclear>` in the `.mei` files. I'm currently letting it to be #unclear-word: light pink with dotted underline. How should I approach this?

For example: https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/51f0921660e2fa5583ebd7bafd44fda2d6585bd5/MEI_outfiles/antiphonae_ad_communionem/003_C03_de-fructu-operum_pem56766_aquit_AQUIT.mei#L201-L203

**Comment by martha-thomae** [comment]
This looks great, @notkaramel!

Don't worry about the `unclear` for now. It is not a special kind of neume, but only means that this was a passage hard to read ("Uncertain reading, unclear neume components" as indicated in the [Conversion Table of GABC to MEI](https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/main/Conversion%20Table%20(GABC%20to%20MEI%20Neumes).md)).

**Comment by martha-thomae** [comment]
Elsa liked the way you have this implemented at the moment. She likes that the text always shows the ornamental neumes in the three fonts even if we just search for one category of them.

**Comment by notkaramel** [comment]
Awesome, I'm glad! :smile:
