### ISSUE TITLE
Filter by mode

### ISSUE THREAD

**Issue by martha-thomae** [ECHOES-from-the-Past/mei-analyser#15]
Add also the functionality to filter by mode when you search.

**Comment by martha-thomae** [comment]
Filter by specific modes (1–8), and with an option to "select all".

**Comment by notkaramel** [comment]
Suggestions:
- Have 9 checkboxes: 1 for `undetected`, 8 for each mode
- Have a `Select All` mode
- Maybe have a textbox to manually input?

**Comment by martha-thomae** [comment]
I would say to have the checkboxes in a dropdown menu (if possible). And to not use a textbox.

**Comment by martha-thomae** [comment]
After consulting with Elsa, she indicated the following checkboxes:

- `Mode 1`
- `Mode 2`
- `Mode 3`
- `Mode 4`
- `Mode 5`
- `Mode 6`
- `Mode 7`
- `Mode 8`
- Undetected

(So, let's forget about the "Select All" thing.)

**Comment by notkaramel** [comment]
Great! Thank you!

**Comment by notkaramel** [comment]
@elsinhadl @martha-thomae Hi Elsa and Martha, here's the markup I created for filter by mode. 
When you select a mode, the search result will be filtered to show only chants of that mode (e.g., `Mode 1` and `Mode 4` is selected, only chants of mode `1` and `4` will be shown on the result table).

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/22058ae2-2c87-4337-9849-ae862c2f0f93)

Here's an alternative with the `All Modes` selection, eventhough Martha told me to forget about it for now :)
![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/563999e0-5712-4fe0-89c2-978c4a8f261c)

**Comment by martha-thomae** [comment]
Hi @notkaramel. 

In here, shouldn't it be more of an "OR" than an "AND"?

> When you select a mode, the search result will be filtered to show only chants of that mode (e.g., Mode 1 and Mode 4 is selected, only chants of mode 1 and 4 will be shown on the result table).

You want to show what is in Mode 4, what is in Mode 1, and that is it (we won't have Mode 1 and Mode 4 coexisting).

**Comment by notkaramel** [comment]
You're right, that was bad wording on my end. I meant to say when user selects mode 1 *and* mode 4, the result will show chants with mode 1 *or* mode 4. Thank you for the correction!

**Comment by martha-thomae** [comment]
I hope I didn't sound too picky. I thought I understood what you meant, but just wanted to make sure that we were on the same page.

**Comment by notkaramel** [comment]
Don't worry, it's all good :smile:

**Comment by elsinhadl** [comment]
Hi Martha and Antoine, I leave a note here because we have to think what happens if a chant is transposed. I believe that the machine would not be able to detect the mode with a high percentage of certainty, right?

**Comment by notkaramel** [comment]
Hi Elsa, can you elaborate/clarify on that?

The machine is able to detect the mode, and it displays the mode with the highest percentage of certainty. E.g., If a Square chant has authentic `mode 1` with 90% and plagal `mode 2` with 50%, the "Mode" column will show "1 (90%)" and filter by mode will be based on it to filter.

If I understand correctly, when a chant is transposed, its mode would also change, right?

**Comment by martha-thomae** [comment]
Yes, @elsinhadl, if you could elaborate on this problem, that would be very helpful. Thank you!

**Comment by elsinhadl** [comment]
Hello, this does not apply to our chants because among the 102 we selected none is given in transposition, therefore we should not worry about this. I was just thinking that when in the future the analytical structure we are creating will be expanded and scaled up to analyse a higher number of chants, the rules given to the machine to recognize the modes must include further specifications because, if the mode is transposed, the finalis, repercussion, meaning of the line and range change. But there is need to worry about this now.
