### ISSUE TITLE
Melodic pattern search

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#20]
Types of queries: 
- SQUARE NOTATION: assign letters to each pitch and ask for a specific series of pitches, e.g. C, D, E, F, G, A, B, c, d, e, f, g, a, b.
- AQUITANIAN NOTATION:
  - if I want to search for a melodic contour and specify just the general intervals (e.g. a second, a third, etc. but without saying if they are major or minor, or if the tone is a whole tone or a semitone), I would just use numbers and their relative distance up or down compared to the previous note using plus “+” and minus “-” followed by a space, the first element is always “X” (followed by a space) to represent a random point of departure, e.g. X +3 +1 -1 -1 +3 0.  (Maximum interval: +8 or -8). In this case the results will bring all the occurrences of that series of intervals regardless of the neume shapes employed.

- The comma signals the neume boundaries; it can be used after each number to signify a series of puncta, e.g, X, +3, +1, -1, -1,+3, 0 . Or it can be used after some numbers to signify pes (“X+1,”), clivis (“X-1,”), torculus (“X+1-1,”), or other neume groupings, e.g. X, +3+1, -1-1, +3, 0 (this could represent, for example C, EF, ED, F, F or F, AB, AG, B, B).

**Comment by martha-thomae** [comment]
This is what was contained in the original "ECHOES - Project Report 2023":

> Pitch similarity to search for specific pitch patterns across the corpus and to gauge the melodic similarity between chants, or portions of chants. However, because we are dealing with chants written in two different music scripts, one more pitch-oriented (square) and the other more interval-oriented (Aquitanian), we must take this into consideration when deciding to what extent the items compared are a good match with the query. For instance, we wish to be able to seek for a specific pitch pattern, e.g. A, G, A, F or for a specific interval pattern, e.g. '2nd up, second down, third up, fifth up'. Ideally, we’d like to be able to search across the whole repertory of chants, or a portion of them (for instance, search the pattern only on some specific sources, or sources with the same kind of musical notation). Obviously, if we seek for a specific pitch pattern, e.g. 'A, G, A, F', this exact pattern could only be found in sources in square notation, while sources in Aquitanian notation can return as a result only a series of intervals,  such as a note followed by a note a second lower, one a second higher, and then one a third lower from one or more sources. 
> 
> Categories of results:
> - A **perfect match**. When I search for a specific series of pitches and the results bring me exactly the same melody
> - An **almost perfect match**. When I search for a specific series of pitches, the results bring me a series of intervals that could match the exact pitches I was looking for, but they are found written in a source in Aquitanian notation.
> - A **very good match**. If the two compared versions show the same melody, but a different note distribution among the syllables. Nota bene:  we are not interested in the text of the syllables but only on the information regarding how many notes are assigned to one or more syllables.
> - A **good match**. If the two compared versions differ for just a few notes (up to 20%, e.g. some notes are missing in one of the two versions or are dislocated at a different height).
> - A **fair match**. When the two versions still bear enough resemblance, but they differ up to 40% notes at several points (e.g. melismas, intonation, cadences) and/or one of the two melodies has a lacuna or uncertain reading.
> - A  **poor match** would be used for melodies that differ by above 40%.
> 
> 
> Other results that would fall into the categories (‘good match’ and ‘fair match’) are for compared versions that show the same pattern but with a few extra ones.

**Comment by martha-thomae** [comment]
The idea of using uppercase letters for lower octaves and lowercase letters for upper octaves comes from the [Guidonian hand](https://upload.wikimedia.org/wikipedia/commons/6/62/Guidonischehand-en.gif) (see the thumb, the palm, and the pinkie in the hand). But it might be a bit confusing as we are using **upper**case for **lower** octave, and **lower**case for **upper** octave. So we can use the regular `c`, `d`, `e`, `f`, `g`, `a`, `b` for the lower octave and the `c'`, `d'`, `e'`, `f'`, `g'`, `a'`, `b'` for the upper octave instead (see the path in the hand after the pinkie).

![](https://upload.wikimedia.org/wikipedia/commons/6/62/Guidonischehand-en.gif)
