### ISSUE TITLE
Visual update to the result table (`File Name` column)

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#22]
- Remove `File Name` column
- Combine `PEM Database` and `Display Chant` (and `File Name`) together
- `File Name` redirects to GABCtoMEI GitHub file
- For chants that has 2 PEM database link (spans two pages)
  - ...
- `Refresh Database` should be executed whenever page is reloaded to improve user experience and reduce confusion

**Comment by elsinhadl** [comment]
A single link just for the page where the chant starts will be enough! Many thanks

**Comment by notkaramel** [comment]
- @martha-thomae Here's what I just marked up for the last column. There can be another column for `Syllable` that contains the ornamental figures for #13 

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/25aa6908-9e62-4669-b6c5-3bb836cca91c)

**Comment by martha-thomae** [comment]
Hi @notkaramel! This was helpful for our discussion today, thank you!

**Comment by martha-thomae** [comment]
In "Search Panel" change "search for chant with the following **notation types**" to "search for chant with the following **music scripts**"
