### ISSUE TITLE
Compatibility issue with different browsers

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#25]
For the majority of this project development, I've been testing features on **Chromium browser** (the Free and Open Source version of Chrome) on Linux.

This means that all features are likely to function as intended on Chromium/Chrome on other operating systems (MacOS, Windows, Linux). However, other common browsers such as Safari, Microsoft Edge, or Vivaldi (that I also use), will behave strangely sometimes.

This will be a backlog issue and not an urgent problem to be solved, but it must be kept in mind for future development.

**Comment by notkaramel** [comment]
On Safari: encountered "Quota Exceeded Error" that makes `Refresh Database` take forever. Thank you @martha-thomae for showing the bug

**Comment by notkaramel** [comment]
Reopens until the issue on Safari is fully resolves

**Comment by notkaramel** [comment]
@martha-thomae can you try on Safari and see if the database loading issue is fixed?

**Comment by martha-thomae** [comment]
I just tried the site and the issue seems to still be there.
![Screenshot 2024-05-26 at 11 38 41 PM](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/13948831/9b154445-1451-41e7-a1dc-fc0185482f90)


One question: didn't we discuss sometime ago to forget about updating/loading the database and just point to a particular commit on the GABCtoMEI repo? Would that fix this? I mean, when we didn't have this loading the database at the beginning, this was not an issue, right?

**Comment by notkaramel** [comment]
> didn't we discuss sometime ago to forget about updating/loading the database and just point to a particular commit on the GABCtoMEI repo?

Yes. The `GABCtoMEI` repo is the source files for all the `.mei` files. The analyser gets those data, parses them, and stores them as `Chant` JSON in the browser's [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). I chose this logic flow to reduce the amount of time needed to parse 100+ chants, which normally takes about 5-10 seconds every search. 

The issue is on the `localStorage` part of this process. Also, the word "Database" might be a little misleading in this context.

> Would that fix this? I mean, when we didn't have this loading the database at the beginning, this was not an issue, right?

No it would not. This became an issue when I start implementing more and more things to be stored in the `Chant` JSON. If I'm not mistaken, before it only has 
```json
{
  "filename": "....mei",
  "neumeComponents": [ ...a list of neume components], 
  "mode": "1"
  "a few more fields": "..."
}
```

but now it has more fields, espeically with the **mode description** being pre-processed and stored to the browser, and the added `syllable` fields for all the texts.

My current judgement is that the mode descriptions are taking up space in Safari's browser limit, hence the issue.

**Comment by notkaramel** [comment]
A solution I have in mind is that instead of storing the chants in the browser, it will be processed here, and GitHub Actions will produce a JSON file to be accessible to the interface. The user would no longer need to manually update the "database" and it would be much easier to work with.

**Comment by notkaramel** [comment]
@martha-thomae can you check on Safari if the compatibility issue is fixed? The architecture is changed now!
