### ISSUE TITLE
Add Number of 'Search Results'

### ISSUE THREAD

**Issue by martha-thomae** [ECHOES-from-the-Past/mei-analyser#35]
Could we add the number of results after each search at the top of the page? Thank you!

**Comment by notkaramel** [comment]
Are you thinking of something like

---
# Chant Results
*41 chants found with the search query* 
/ TABLE /

---

**Comment by martha-thomae** [comment]
Yes, exactly!

**Comment by notkaramel** [comment]
![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/e9f02e4a-4625-4f43-8b7c-fbcebf7e350b)

I will add this as part of PR #32 since it's a very small change that can be helpful for development on that branch too.
