### ISSUE TITLE
Add `clef` field to Chant encoding

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#52]
_Originally posted by @martha-thomae in https://github.com/ECHOES-from-the-Past/mei-analyser/issues/34#issuecomment-2132402483_

| IF last note | AND for every nc with tilt="se" | THEN: | comments | pitch at line |
| -- | -- | -- | -- | -- |
| loc = -2 | loc = -1   OR  loc = +3 | mode = 1 |   | f |
loc = 0 | loc = +1  OR  loc = -2 | mode = 2 |   | d |
loc = -2 | loc = -2   OR  loc = +2 | mode = 3 |   | g |
loc = -1 | loc = -1   OR  loc = +3 | mode = 4 |   | f |
loc = 0 | loc = 0    OR  loc = +4  OR  loc = -3 | mode = 4 | (rare case, earlier chants) | e |
loc = -2 | loc = +1  OR  loc = -3 | mode = 5 |   | a |
loc = 0 | loc = -1   OR  loc = +3 | mode = 6 |   | f |
loc = -2 | loc = 0    OR  loc = +3 | mode = 7 |   | b |
loc = 0 | loc = +2  OR  loc = -2 | mode = 8 |   | g |

I was thinking adding a `clef` field to the Chant object. For Aquitanian chant, it will follow the table above, and for Square chant, it will be the clef field (like [this line](https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/8daceb737bb3b8d4b3cef52950ecd4fd3087f222/MEI_outfiles/antiphonae_ad_communionem/002_C02_benedicite-omnes_pem85041_square_SQUARE.mei#L40)). What do you think?

**Comment by martha-thomae** [comment]
So, for square notation would it look like `C4` (for C clef in four line) or `F2` (for F clef in second line)?

For Aquitanian, could you give me some examples of how it will look like?

**Comment by notkaramel** [comment]
I was thinking something like this

```json
/* Square */
{
   "clef": {
      "line": 2
      "shape": "C"
   }
}

/* Aquitanian */
{
   "clef": {
      "line": 0
      "shape": "F"
   }
}
```

This way, it's more consistent with the `mei` file for Square chants, IMO. It's also harder to process `chant.clef` when it's sometimes `F2` for Square and just `G` for Aquitanian.

**Comment by martha-thomae** [comment]
Ah, got it! That looks fine with me :)
