### ISSUE TITLE
Melodic Density Analysis

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#7]
# Description/Goal
To measure the distribution of pitches across syllables (number of notes per syllable)

According to the **ECHOES Project Report 2023**:
> Melodic density to measure the distribution of pitches across the syllables. Knowing the syllables that bear the highest number of notes would make it possible to discover if there are any words that are most likely to bear a melisma. Furthermore, finding out where the syllables bearing the highest melodic density are located within the chant (i.e., at the beginning, end, or middle of the chant) can help us to unveil recurring neume patterns employed at cadences.

As pointed out by @elsinhadl:
- This search should be done over the whole corpus.
- Look for syllables with 6 or more notes (i.e. neume components) in them.
- Return the list of syllables, with a link to the chant that contains them. When clicking the link, the chant should be opened and displayed on a new tab (so, the MEI file should be rendered in the new tab).

**Comment by martha-thomae** [comment]
As indicated in https://github.com/ECHOES-from-the-Past/mei-analyser/issues/22#issuecomment-2036835204, the result should be displayed on an extra column with heading 'Text'. This column should contain the full text of the chant, with the syllables that contain melismas (6 notes or more per syllable) in a different color.

**Comment by martha-thomae** [comment]
So, the results of the melodic density will be highlighted in the text with a background color. This color could be light green or similar so that the font color used to signal the ornamental neumes (liquescent, oriscus, and quilisma) is still visible.

**Comment by notkaramel** [comment]
I'll try to find colours that would work with all ornamental text and the melisma background. Here's a preview of what it would look like: 

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/c99bb08c-f52b-4d19-a1e7-0a7d22c0350a)

With ornamental neumes:

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/c951323d-f1b0-418f-aa15-7bd72c460c9c)

**Comment by elsinhadl** [comment]
Hi! I don't mind the color selection to show the melodic density, what is crucial to me is that the background colors allow to recognize the yellow, blue and fuchsia (used for ornamental neumes) in case a syllable with a certain melodic density contains them. Thank you!

**Comment by notkaramel** [comment]
Thank you! That's exactly what I was aiming for.

**Comment by martha-thomae** [comment]
@notkaramel: After you have implemented this for 6-note melismas, the next step would be to allow the user to choose the number of notes in the melismas (a minimum of 6 and a maximum of 12).

@elsinhadl, could you double-check that these were the numbers we agreed on?

**Comment by notkaramel** [comment]
@martha-thomae Here's the input box that allows user to highlight every syllable that has at least *`the number in the box`* number of notes. For example, if the number is `7` (like below), when the user click on the `Search` button, all syllables with 7+ notes will be highlighted.

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/a5df28d2-8bf5-4bd8-9998-52ba028b6fa6)

Search result when the melisma box shows `6`:

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/7588f3db-f1ea-4bee-b063-9adf99845dac)

Search result when the melisma box is `7`: (notice less syllables are highlighted here)

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/737344b3-caa6-4b14-8433-729b7d5e9439)

You can try it out on branch `melodic-density`

**Comment by elsinhadl** [comment]
hello! I love the input box but maybe we should clarify somewhere that it searches for syllable that contain "at least" _number in the box_ notes.

**Comment by elsinhadl** [comment]
> @notkaramel: After you have implemented this for 6-note melismas, the next step would be to allow the user to choose the number of notes in the melismas (a minimum of 6 and a maximum of 12).
> 
> @elsinhadl, could you double-check that these were the numbers we agreed on?

Yes, these were the numbers we agreed on but actually I think that the "input box" solves our problems and allows a great flexibility. Maybe there is no need to have categories if we can use the input box

**Comment by martha-thomae** [comment]
> hello! I love the input box but maybe we should clarify somewhere that it searches for syllables that contain "at least" number in the box notes.

What about instead of saying: `Melisma (#notes in a syllable) [ ]`

We do:
`Melisma (**minimum** #notes in a syllable) [  ]`

Or maybe:

```
Melismatic Search:
Looking for syllables with melismas of at least [ ] notes
```

**Comment by martha-thomae** [comment]
> Yes, these were the numbers we agreed upon but actually I think that the "input box" solves our problems and allows great flexibility. Maybe there is no need to have categories if we can use the input box. I am happy with this solution!

Hi @elsinhadl, yes, we won't have categories, just the box with numbers that can go from a minimum of 6 to a maximum of 12. Does that sound good to you?

**Comment by elsinhadl** [comment]
Hello,
I wonder if the numbers in the box can go from 2 to a max of 20. Would that a problem to change the current numbers?

**Comment by notkaramel** [comment]
@elsinhadl Hi Elsa,

I can make the box go from 2 to 20. The only problem (more like a slight inconvenient) is that the user would have to click a lot of times to reach the maximum value, or to decrease it.

**Comment by notkaramel** [comment]
@martha-thomae I'm so sorry I forgot about updating the wordings of the melisma search. Will open a quick PR to patch it
