### ISSUE TITLE
Chart analysis for chants

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#70]
- We will probably display two diagrams:
  - [x] Frequency focused: Sort the note repetition in descending order
  - [x] All notes in order (pitch + octave), visually showing the ambitus
- [x] Stacking rhombus on top of note counts column

**Comment by notkaramel** [comment]
This feature will be pushed along with the code refactoring update

**Comment by notkaramel** [comment]
A quick update of the current state of this issue:

![image](https://github.com/user-attachments/assets/0bd5f423-8ecd-43df-ac73-eaabef6b6f68)

**Comment by martha-thomae** [comment]
Summary:
- [ ] Keep only the second diagram
- [ ] Change the title to "Frequency of the notes across the chant ambitus"
- [ ] Label the x-axis as "Ambitus"
- [ ] Label the y-axis as "Frequency"
- [ ] Include (for now) all the notes from the lowest to the highest in the x-axis
- [ ] Keep the hovering for looking at the values of the bars in the graph (they are great!)
- [ ] And only include rhombuses for Aquitanian

**Comment by martha-thomae** [comment]
- [ ] Remove the "rhombus" part of the key for square notation
- [ ] Check the order of the pitches with octaves in the x-axis for square notation
- [ ] For Aquitanian notation, there are duplicate values in the x-axis
- [ ] For Aquitanian notation, the green bar should only include the number of pitches without counting rhombuses.

**Comment by notkaramel** [comment]
All done!
