### ISSUE TITLE
Filter by finalis

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#71]
Adding the ability to filter chants by its finalis. It's a new feature to be placed underneath *Filter by melodic pattern*
- Exact Pitch
- Location in relation to the line

**Comment by martha-thomae** [comment]
These two ways of looking for a finalis (pitch or location) constitute the same implementation, so there is no need for radio buttons for each. Instead, we can add a tooltip and clarify that people can search for pitch values in square notation (from `a`-`g`) and location values in Aquitanian notation (from `-3` to `+4`).

**Comment by martha-thomae** [comment]
Thanks, Antoine. Maybe giving also a range of values might be useful for the user?
