### ISSUE TITLE
Detection of Chant Mode in Aquitanian Notation

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#8]
# Description
We want to recognize the mode of the chant if there is any semitonal information available in the notation. We can detect this by looking at the **_finalis_** and the placement of the _**rhomboidal punctum**_.

# Modes (Aquitanian notation)
> Referecing the ECHOES - Project Report 2023
## 1st mode
- The last note(D) is placed two steps below the line (the note on the line is F).
- The rhomboidal punctum can be found exclusively one step below the line (E) or three steps above the line (B)

## 2nd mode
- The last note (D) is placed on the line.
- The rhomboidal punctum can be found exclusively one step above the line (E) or two steps below the line (B)

## 3rd mode
- The last note (E) is placed two steps below the line (the note on the line is G).
- The rhomboidal punctum can be found exclusively two steps below the line (E) or two steps above the line (B)

## 4th mode
- The last note (E) is placed one step below the line (F).
- The rhomboidal punctum can be found exclusively one step below the line (E) or three steps above the line (B)

## 4th mode, special case (showing greater antiquity)
- The last note (E) placed on the line.
- The rhomboidal punctum can be found exclusively on the line (E) or four steps above the line (B), or three steps below the line (B).

## 5th mode
- The last note (F) is placed two steps below the line (A).
- The rhomboidal punctum can be found exclusively one step above the line (B) or three steps below the line (E)

## 6th mode
- The last note (F) is placed on the line.
- The rhomboidal punctum can be found exclusively one step below the line (E) or three steps above the line (B)
- It is rare, but occasionally in the 6th mode the rhomboidal punctum is used for the pitch A. The rhomboidal punctum signals the lower note of the semitone and, in this case, hints that the B is flat. In other words, the distance between A and B is a semitone. In the 6th mode the repercussio (=most repeated note) is A.

## 7th mode
- The last note (G) is placed two steps below the line (B).
- The rhomboidal punctum can be found exclusively on the line (B) or three steps above the line (E)

## 8th mode
- The last note (G) is placed on the line.
- The rhomboidal punctum can be found exclusively two step above the line (B) or two steps below the line (B)

**Comment by martha-thomae** [comment]
Here is the summary of those previous rules in terms of MEI attributes and values:

| IF | AND | THEN: | comments |
| -- | -- | -- | -- |
| **last note** | **for every nc with tilt="se"** |  |  |
| loc = -2 | loc = -1   OR  loc = +3 | mode = 1 |  
loc = 0 | loc = +1  OR  loc = -2 | mode = 2 |  
loc = -2 | loc = -2   OR  loc = +2 | mode = 3 |  
loc = -1 | loc = -1   OR  loc = +3 | mode = 4 |  
loc = 0 | loc = 0    OR  loc = +4  OR  loc = -3 | mode = 4 | (rare case, earlier chants)
loc = -2 | loc = +1  OR  loc = -3 | mode = 5 |  
loc = 0 | loc = -1   OR  loc = +3 | mode = 6 |  
loc = -2 | loc = 0    OR  loc = +3 | mode = 7 |  
loc = 0 | loc = +2  OR  loc = -2 | mode = 8 |  

Let me know how this goes :)

**Comment by martha-thomae** [comment]
Further things to keep in mind (don't worry about these now @notkaramel, these are just to keep in mind after we are done:

- It is rare, but occasionally in the 6th mode the rhomboidal punctum is used for the pitch A. The rhomboidal punctum signals the lower note of the semitone and, in this case, hints that the B is flat. In other words, the distance between A and B is a semitone. In the 6th mode the repercussio (=most repeated note) is A.
- Liquescence may be occasionally used to signal the lower note of the semitone (that is, E or B).

**Comment by martha-thomae** [comment]
Would you mind providing a similar summary for the rules for mode detection for square notation, @elsinhadl ? I mean, similar to the way you provided them for the ECHOES report. Thank you!

**Comment by notkaramel** [comment]
- Update 19/02/2024: I just pushed the feature to detect chant mode for Aquitanian notation. 
- @martha-thomae I have a question: for example, to statisfy mode 1, can the list of rhomboidal punctums (nc with tilt `se`) both has `loc = -1` and `loc = 3`? Or is it strictly either only `loc = -1` or only `loc = 3`, exclusively (xor relation).

**Comment by martha-thomae** [comment]
> * @martha-thomae I have a question: for example, to statisfy mode 1, can the list of rhomboidal punctums (nc with tilt `se`) both has `loc = -1` and `loc = 3`? Or is it strictly either only `loc = -1` or only `loc = 3`, exclusively (xor relation).

Hi @notkaramel! It is both, it is an "inclusive or" (one, the other, or both).

**Comment by notkaramel** [comment]
@martha-thomae Thank you! I implemented it correctly.

**Comment by elsinhadl** [comment]
Dear Martha and Antoine,
I have just added on p. 11 in the Project Report
https://docs.google.com/document/d/17bPC6Z9KSgKCxt_50-8Apsu1MAdyA-Pq13Hs2h778-0/edit?usp=sharing
the rules for identifying the mode of chants written in square
notation ("Teaching
the machine how to identify the mode of chants written in square notation").
Please let me know if anything is unclear.
Many thanks,
Elsa



*________________________________________________________*

PI of *Echoes from the Past: Unveiling a Lost Soundscape with Digital
Analysis
<https://sites.google.com/fcsh.unl.pt/elsadeluca/echoes-research-project> *
(2022.01957.PTDC)

Recent publication: *The Materiality of Sound in ChantManuscripts in the
West
<https://www.brepols.net/products/IS-9782503606149-1?fbclid=IwAR2gxS-ucQAfNZEgO9rjGSbBUcpXbSKBkictNRCHw5uqWjfIDCw0oyhYpso>*,
Brepols 2023


CESEM - Centre for the Study of the Sociology and Aesthetics of Music
IN2PAST – Associate Laboratory for Research and Innovation in Heritage,
Arts, Sustainability and Territory
School of Social Sciences and Humanities
NOVA University of Lisbon

https://sites.google.com/fcsh.unl.pt/elsadeluca/ |
*https://cesem.fcsh.unl.pt/en/pessoa/elsa-de-luca-2/
<https://cesem.fcsh.unl.pt/en/pessoa/elsa-de-luca-2/> *



Antoine Phan ***@***.***> escreveu (segunda, 19/02/2024 à(s)
18:50):

**Comment by martha-thomae** [comment]
There were a few issues found by @elsinhadl, so I made the following modifications on a separate branch:
1. We were missing a default `mode=-1` case when there simply are no rhombuses at all in the chant (https://github.com/ECHOES-from-the-Past/mei-analyser/commit/aa9cc2e5d1d338016a129c62a7858c08e3d03c76)
2. There was a minor error in some of the flags for the location of rhombuses (the use of an ‘or’ instead of an ‘and’ statement) (https://github.com/ECHOES-from-the-Past/mei-analyser/commit/e2ca0cfded48c86a4afdcf54e4d2914a02b29f47) 
3. I modified the change I just reported on **item 1**, so that it doesn't detect any mode (it returns `mode = -1`) not only when there are no rhombuses but also when there is only one rhombus in the whole chant. I made this change because @elsinhadl indicated that one rhombus is not enough to convey mode information (https://github.com/ECHOES-from-the-Past/mei-analyser/commit/e61c79a319fb6964033fd056defc89da9793feae).

I won't attempt to make a pull request until you have finished with the refactoring :)

**Comment by notkaramel** [comment]
Thank you @martha-thomae! I realized the logic that I implemented (using `filter()`) is incorrect and actually producing false results (it just coincidentally happens that most detectable chants are either mode 1 or 6, which is the first `if` block). There was a default `mode=-1` at the very end of each condition blocks in fact, but I prefer your implementation to be honest :)

And yes, I will keep you updated once the refactoring of the interface is completed so we can discuss more about the mode detectioin.

**Comment by martha-thomae** [comment]
> There was a default mode=-1 at the very end of each condition blocks in fact

Yes, I saw this. And I kept this as well for any other cases that do not fall into the previous categories.

> I realized the logic that I implemented (using filter()) is incorrect and actually producing false results (it just coincidentally happens that most detectable chants are either mode 1 or 6, which is the first if block).

Yes, I saw that. But it was just a small thing about negations and their interaction with OR / AND connectors. It was fine, the logic was there, it was just the wrong connector (so I added some comments for it to be more clear as well). It is working now. I checked everything against Elsa's table. I am just left with a few questions that I sent over email.

**Comment by martha-thomae** [comment]
With the changes I detailed here, we have solved the issue of mode detection for the chants in Aquitanian notation. I went through the chants with Elsa and the algorithm detects the right mode for every single one of them (except for on where there is a scribal error, the scribe made a rhombus in the wrong place). So we are all good here. Maybe, for the future, including some extra information about how the chant mode was detected would be good (adding the number of rhombuses for each note, and the value of the finalis).

> There were a few issues found by @elsinhadl, so I made the following modifications on a separate branch:
> 
> 1. We were missing a default `mode=-1` case when there simply are no rhombuses at all in the chant ([aa9cc2e](https://github.com/ECHOES-from-the-Past/mei-analyser/commit/aa9cc2e5d1d338016a129c62a7858c08e3d03c76))
> 2. There was a minor error in some of the flags for the location of rhombuses (the use of an ‘or’ instead of an ‘and’ statement) ([e2ca0cf](https://github.com/ECHOES-from-the-Past/mei-analyser/commit/e2ca0cfded48c86a4afdcf54e4d2914a02b29f47))
> 3. I modified the change I just reported on **item 1**, so that it doesn't detect any mode (it returns `mode = -1`) not only when there are no rhombuses but also when there is only one rhombus in the whole chant. I made this change because @elsinhadl indicated that one rhombus is not enough to convey mode information ([e61c79a](https://github.com/ECHOES-from-the-Past/mei-analyser/commit/e61c79a319fb6964033fd056defc89da9793feae)).
> 
> I won't attempt to make a pull request until you have finished with the refactoring :)

**Comment by notkaramel** [comment]
I think we can write up a wiki page for mode detection, using all the information from this issue.
