### ISSUE TITLE
Search by metadata

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#84]
- Search by Title
- Source
- Cantus ID (@martha-thomae needs to include that in the files, it is not there yet)

**Comment by martha-thomae** [comment]
The Cantus ID is now in the MEI files like this:
https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/0dd668d0c3722dddc542ed33777a22bea82faa45/MEI_outfiles/antiphonae_ad_communionem/001_C01_benedicite-omnes_pem82441_aquit_AQUIT.mei#L8-L11

**Comment by martha-thomae** [comment]
Suggestion:

To have three dropdown menus, one for title, one for source, and one for Cantus ID.

The dropdown menus will have the values preloaded (avoid repetition).

**Comment by notkaramel** [comment]
- Ability to click on the result to have it show up in the textbox
- Using arrow button to scroll up/down the result, and `Enter` to select

**Comment by notkaramel** [comment]
- As we discussed, we will pause this issue for now due to the UI element implementation's complication.

    "It would be easier to use a UI library like [this combo box from bits-ui](https://bits-ui.com/docs/components/combobox) instead of manually implement all of it for the interface." - said me

- A concern is the sustainability of the project in the future, as this adds more than one dependencies and add complexities to the project. I decided to merge #94 to version `0.5.8`, and will work on adding elements along with an adjacent issue #93
