### ISSUE TITLE
Search by text

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#87]
And it shouldn't be limited by syllable boundaries

**Comment by notkaramel** [comment]
Should be able to search for partial/part of a word, and able to search for a specific order of words

**Comment by notkaramel** [comment]
For now, the search is case insenitive and take into account spaces

- I'm thinking of adding white space removal (via Regexp) but I'm unsure how relavent or important it would be.
- Can also add user options for "Case Sensitive", "Ignore Spaces", etc.

**Comment by martha-thomae** [comment]
It should consider spaces and it is fine if it is case insensitive (for now), we would need to ask @elsinhadl

**Comment by elsinhadl** [comment]
Yes, I agree that it is fine if it is case insensitive. Spaces can be important as they signal word boundaries. Thank you.

**Comment by notkaramel** [comment]
Thank! It's now resolved

Commit: 7a29cf08dd168d93ed14038ac450bb629118949f
