### ISSUE TITLE
Entire corpus search

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#9]
# Description
- Add functionality to perform search on all existing chants (`.mei` files) in the database

# Requirements
- [x] When search functionality is selected (user clicks on the `Search` button), the search query is applied to all chants in the database
- [x] If there is a match (pitch pattern, ornamental shape, etc.), display the chant/the name of the chant
- [x] The user can select/click on the chant or its name to display the search results

**Comment by notkaramel** [comment]
Added some system requirements to the feature. Some ideas are: 
- Store every chants in the database using the `Chant` object abstraction and save them to `sessionStorage` or `localStorage`. The data is then retrieved to perform the search, instead of fetching/parsing all chants everytime `Search` is selected.
- Separating the user interface into two different modes: **search mode display**, and **analysis mode display**. The interface would contain:
  - **Search mode**: a search textbox, ornamental shapes options, a list/table of chants with the search result, a display of one chant when selected from the list.
  - **Analysis mode**: similar to current interface

**Comment by notkaramel** [comment]
- Note that this feature is also partly covering #7

**Comment by martha-thomae** [comment]
@notkaramel, I added the links to the original images now in the MEI files so you can retrieve them from the files themselves. See https://github.com/ECHOES-from-the-Past/GABCtoMEI/pull/3 to check where they URL for the image is located.

**Comment by notkaramel** [comment]
> moved comment from issue #10 

@martha-thomae is it normal that lots of chants have the same link to the PEM Database? (This is currently on http://server.notkaramel.me/mei-analyser/)

![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/0dd72199-462e-44e0-9451-3c490832af4f)
