### ISSUE TITLE
Wildcard Search: Regular Expression for pitch height (Aquitanian `@loc`)

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#91]
- This is the continuation of #65
- As discussed in one of our meetings, since wildcard search is super powerful and easy to add things on now, it is very simple to add a search for pitch height for Aquitanian chants.
- Example: `1 +2 3? -1 0 -1{2}` would return find occurrences of `1 2 -1 0 -1 -1` or `1 2 3 -1 0 -1 -1`
- Possible issue: since the current implementation is that after search regexp is constructed, it is used to match with a string of all pitches all concatenated, meaning "-1" would be counted as two indecies, potentially break the index remapping step to find the pattern

**Comment by martha-thomae** [comment]
You would need to consider the sign and the number as a token. So not compare string against string, but list against list. In the case of pitches it works because the list of notes against the list of notes is the same as comparing the string against the string.

**Comment by notkaramel** [comment]
Current state of the tooltip for version 0.5.9:

![image](https://github.com/user-attachments/assets/cd90457f-1958-45ea-af65-4bf7c0ed2802)

We can close this issue now :)
